# Generated by Django 5.1.3 on 2025-01-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderlocation',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
