# Generated by Django 5.1.3 on 2025-01-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('service_type', models.CharField(blank=True, max_length=150, null=True)),
                ('citizenship_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='kyc/photos/')),
                ('citizenship_photo', models.ImageField(upload_to='kyc/citizenship_photos/')),
                ('training_certificate', models.ImageField(upload_to='kyc/training_certificates/')),
                ('is_verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
