# Generated by Django 5.1.3 on 2025-01-19 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycverification', '0003_alter_kyc_service_provider'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='userauth.serviceprovider'),
        ),
    ]
